"""Mesh and output helpers replacing Easy3D/libigl utilities."""
from __future__ import annotations

import json
from pathlib import Path
import numpy as np
import trimesh


def load_mesh(path: str | Path) -> trimesh.Trimesh:
    loaded = trimesh.load_mesh(path, process=True)
    if isinstance(loaded, trimesh.Scene):
        loaded = trimesh.util.concatenate(tuple(loaded.geometry.values()))
    if not isinstance(loaded, trimesh.Trimesh) or len(loaded.faces) == 0:
        raise ValueError(f"Could not load a triangular mesh from {path}")
    if not loaded.is_watertight:
        loaded.remove_unreferenced_vertices()
    return loaded


def normalize(mesh: trimesh.Trimesh) -> tuple[np.ndarray, float]:
    """原地平移、缩放到单位球，并返回原中心和尺度。"""
    center = mesh.vertices.mean(axis=0)
    mesh.vertices -= center
    scale = float(np.linalg.norm(mesh.vertices, axis=1).max())
    if scale > 1e-12:
        mesh.vertices /= scale
    return center, scale


def face_data(mesh: trimesh.Trimesh) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    centers = mesh.triangles_center
    normals = mesh.face_normals
    adjacency = mesh.face_adjacency
    # The adjacency edge is available directly and avoids assumptions about face winding.
    edge_lengths = (
        np.linalg.norm(
            mesh.vertices[mesh.face_adjacency_edges[:, 0]]
            - mesh.vertices[mesh.face_adjacency_edges[:, 1]],
            axis=1,
        )
        if len(adjacency)
        else np.empty(0)
    )
    if len(adjacency):
        first_normals = normals[adjacency[:, 0]]
        second_normals = normals[adjacency[:, 1]]
        cross_norm = np.linalg.norm(np.cross(first_normals, second_normals), axis=1)
        dot_value = np.sum(first_normals * second_normals, axis=1)
        angles = np.arctan2(cross_norm, dot_value)
    else:
        angles = np.empty(0)
    return centers, normals, adjacency, np.column_stack((angles, edge_lengths))


def save_labels(mesh: trimesh.Trimesh, labels: np.ndarray, path: str | Path) -> None:
    mesh_copy = mesh.copy()
    colors = np.zeros((len(mesh.faces), 4), dtype=np.uint8)
    fillet = labels.astype(bool)
    colors[fillet] = [220, 70, 55, 255]
    colors[~fillet] = [90, 130, 180, 255]
    mesh_copy.visual.face_colors = colors
    mesh_copy.export(path)


def save_field(mesh: trimesh.Trimesh, field: np.ndarray, path: str | Path) -> None:
    mesh_copy = mesh.copy()
    values = np.asarray(field, dtype=float)
    lo, hi = values.min(initial=0.0), values.max(initial=1.0)
    t = (values - lo) / max(hi - lo, 1e-12)
    colors = np.column_stack(
        (255 * t, 70 + 130 * (1 - t), 220 * (1 - t), np.full(len(t), 255))
    )
    mesh_copy.visual.face_colors = colors.astype(np.uint8)
    mesh_copy.export(path)


def save_json(data, path: str | Path) -> None:
    Path(path).write_text(json.dumps(data, indent=4), encoding="utf-8")


def save_point_cloud(
    cloud: trimesh.points.PointCloud,
    path: str | Path,
    normals: np.ndarray | None = None,
) -> None:
    """Export a PLY point cloud with the normal fields used by Easy3D."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    points = np.asarray(cloud.vertices, dtype=float).reshape((-1, 3))
    if normals is None:
        normals = np.zeros_like(points)
    normals = np.asarray(normals, dtype=float).reshape((-1, 3))
    if len(normals) != len(points):
        raise ValueError("Point-cloud normal count must match point count")
    header = (
        "ply\nformat ascii 1.0\ncomment generated by defillet_py\n"
        f"element vertex {len(points)}\n"
        "property float x\nproperty float y\nproperty float z\n"
        "property float nx\nproperty float ny\nproperty float nz\nend_header\n"
    )
    rows = "".join(
        f"{point[0]:.17g} {point[1]:.17g} {point[2]:.17g} "
        f"{normal[0]:.17g} {normal[1]:.17g} {normal[2]:.17g}\n"
        for point, normal in zip(points, normals)
    )
    path.write_text(header + rows, encoding="ascii")
